version: "3.8"

services:
  postgres:
    image: "postgres:14"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "35432:5432"
    networks:
      - postgres

  app:
    depends_on:
      - postgres
    image: 'app:1.0-SNAPSHOT'
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    expose:
      - "8337"
    ports:
      - "8337:8337"
    networks:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/postgres

networks:
  postgres:
    driver: bridge